name: PixelOS Mondrian Crave Hack

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Crave
        run: |
          curl -sL -o crave https://github.com/accupara/crave/releases/download/0.2-7193/crave-0.2-7193-linux-amd64.bin
          chmod +x crave
          sudo mv crave /usr/local/bin/crave
          /usr/local/bin/crave --version || true

      - name: Configure Crave
        run: |
          mkdir -p ${HOME}/.config/crave
          cat << 'EOF' > ${HOME}/.config/crave/crave.conf
          ${{ secrets.CRAVE_CONF }}
          EOF
          chmod 600 ${HOME}/.config/crave/crave.conf

      - name: Run Build inside Crave Cloud
        run: |
          git remote set-url origin https://github.com/accupara/crave-workspaces.git
          /usr/local/bin/crave -k -c ${HOME}/.config/crave/crave.conf -v run --no-patch -- bash build.sh

      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: PixelOS-mondrian
          path: ./*.zip
          if-no-files-found: ignore
