name: Test Server Power

on:
  workflow_dispatch: # Эта строчка добавляет кнопку ручного запуска

jobs:
  test-run:
    runs-on: self-hosted # КРИТИЧЕСКИ ВАЖНО: говорит GitHub использовать ВАШ сервер

    steps:
      - name: Очистка рабочего пространства
        run: rm -rf *

      - name: Проверка характеристик сервера
        run: |
          echo "=== Процессор (Количество потоков) ==="
          nproc
          echo "=== Оперативная память ==="
          free -h
          echo "=== Свободное место на диске ==="
          df -h /
          
